# Количество реплик Pod'ов
replicaCount: 2
# Настройки образа контейнера
image:
 repository: nginx # Репозиторий Docker образа
 tag: "1.21" # Тег образа (версия)
 pullPolicy: IfNotPresent # Политика загрузки: Always, IfNotPresent, Never
# Настройки Service
service:
 type: ClusterIP # Тип Service: ClusterIP, NodePort, LoadBalancer
 port: 80 # Порт Service
# Дополнительные настройки (уже есть в сгенерированном Chart)
imagePullSecrets: [] # Секреты для загрузки образов
nameOverride: "" # Переопределение имени
fullnameOverride: "" # Переопределение полного имени